### ISSUE TITLE
Unable to run on 32bit Raspberry Pi

### ISSUE THREAD

**Issue by johnstorey** [cryptoscope/ssb#77]
I followed the instructions to compile on

Raspberry Pi 4
Raspbian Lite, 32bit OS
Go 1.14 
Compiled on the pi itself

When I attempt to run go-sbot as follows

> $GOPATH/bin/go-sbot

I get the following error. Any ideas? I am new to scuttlebutt, so please forgive stupid mistakes.

> t=612.141µs starting=metrics addr=localhost:6078
> 2021/02/07 11:50:19 dropping empty lockflile /home/pi/.ssb-go/indexes/groups/keys/mkv/.11eaa770cd0c84e0bf7a8f6c7e51040b6ea1ac4e
> 2021/02/07 11:50:19 dropping empty lockflile /home/pi/.ssb-go/indexes/groups/keys/mkv/.342aaf809784f0cdd40211c942c053729a833a0a
> go-sbot: failed to instantiate ssb server: sbot: failed to open sublog for add-member messages: mlog/badger: badger failed to open: Map log file. Path=/home/pi/.ssb-go/sublogs/group-member-helper/badger/000000.vlog. Error=cannot allocate memory
> 
>

**Comment by cryptix** [comment]
Hey @johnstorey, thanks for giving it a spin.

Yes, I have a hunch this is a known issue, related to mmio, though the error could be more forthcoming.

Try building with `go build -tags nommio` and please report back if it fixes the problem.

**Comment by johnstorey** [comment]
@cryptix thanks, I was able to compile and start go-sbot successfully. It cannot follow my Patchwork id on a machine  (unexpected JSON value), and Patchwork does not see it as something to follow,  but no doubt that is due to my unfamiliarity with scuttlebutt.

I got the sense from reading scuttlebutt channels that the new development was slowly going on in Rust. What is your intent for this codebase? Are you planning to keep it around, or are you headed for the Rust codebase?

Meanwhile I'll close this ticket. Thanks again!

**Comment by johnstorey** [comment]
Resolved

**Comment by cryptix** [comment]
> unexpected JSON value

This is the same issue as #79 - working on it.


> Are you planning to keep it around, or are you headed for the Rust codebase?

I intend to keep it around. At least for a year or two and try to get some contributors. If that fails, I will re-evaluate but I have a lot of mixed feelings about rust and might try something different. (Like, I cant believe [errors are still such a hot potato](https://msirringhaus.github.io/Where-everything-went-wrong/), this and async makes me think that they re-produce the worst aspects of the npm culture, like numerous custom flow control libs resulting in bad compose-ability across crates/modules)
